### ISSUE TITLE
Esquema E/R

### ISSUE THREAD

**Issue by AVegMor** [Javviviii2/Moodle#1]
Veo un par de cosas a mejorar de tu esquema E/R:

- Tienes varias tablas que se llaman igual (tiene), esto te va a dar error. Además que dentro de ellas tienes varios atributos con el mismo nombre. Te aconsejo que los id de cada tabla le pongas nombres más descriptivos p. ej.: id_usuario, id_actividad...
- Añade la cardinalidad a las tablas.
- En usuario tienes el atributo rol, si van a existir varios roles en la aplicación, te recomiendo que lo saques a una entidad aparte. 
- Te aconsejo usar la misma nomenclatura para los nombres de atributos y tablas, por ejemplo tienes algunos atributos que comienzan en mayúsculas y otros no.

**Comment by Javviviii2** [comment]
En relación a la creación de la tablas y relaciones es moodle quién lo hace. Tras investigar el código fuente, el paquete moodle ya trae el código para crear la estructura de la base de datos:

- Código fuente -> https://github.com/moodle/moodle/blob/main/lib/db/install.xml
- Información sobre las estructuras elementales -> https://docs-moodle-org.translate.goog/dev/Database_schema_introduction?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=sc
- Imagen -> https://www.examulator.com/er/3.5/

Por tanto, ese esquema E/R no sería el real, sino más parecido a la imagen que paso: [moodle 3.5](https://www.examulator.com/er/3.5/).

**Comment by AVegMor** [comment]
Pero en tu anteproyecto has incluído un esquema E/R con la relación entre usuarios, cursos, actividades.... ¿No lo vas a utilizar? Si no lo vas a utilizar quítalo del anteproyecto.

**Comment by Javviviii2** [comment]
Vale, ya lo he cambiado.
